
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 07 19:39:27 COT 2025
//----------------------------------------------------

package anal;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Jun 07 19:39:27 COT 2025
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\043\000\002\002\004\000\002\002\006\000\002\002" +
    "\005\000\002\011\003\000\002\011\005\000\002\012\003" +
    "\000\002\012\003\000\002\012\005\000\002\012\005\000" +
    "\002\007\005\000\002\007\005\000\002\007\005\000\002" +
    "\007\014\000\002\007\012\000\002\007\011\000\002\007" +
    "\013\000\002\007\011\000\002\007\006\000\002\007\006" +
    "\000\002\007\007\000\002\013\003\000\002\013\004\000" +
    "\002\014\011\000\002\014\006\000\002\010\003\000\002" +
    "\010\004\000\002\005\005\000\002\005\003\000\002\006" +
    "\005\000\002\006\003\000\002\003\005\000\002\003\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\134\000\004\022\004\001\002\000\022\005\010\015" +
    "\015\020\014\021\007\024\013\027\011\033\020\037\012" +
    "\001\002\000\004\002\006\001\002\000\004\002\001\001" +
    "\002\000\006\005\131\016\130\001\002\000\024\005\027" +
    "\013\032\015\015\020\014\021\007\024\013\027\011\033" +
    "\020\037\012\001\002\000\004\006\114\001\002\000\004" +
    "\005\077\001\002\000\004\006\071\001\002\000\004\005" +
    "\062\001\002\000\004\005\062\001\002\000\042\005\027" +
    "\015\015\020\014\021\007\023\uffe9\024\013\026\uffe9\027" +
    "\011\031\uffe9\032\uffe9\033\020\036\uffe9\037\012\040\uffe9" +
    "\041\uffe9\042\uffe9\001\002\000\004\023\060\001\002\000" +
    "\004\005\021\001\002\000\004\013\022\001\002\000\004" +
    "\004\023\001\002\000\004\034\024\001\002\000\004\005" +
    "\025\001\002\000\024\005\027\015\015\020\014\021\007" +
    "\024\013\027\011\033\020\035\026\037\012\001\002\000" +
    "\004\004\055\001\002\000\004\013\032\001\002\000\004" +
    "\036\031\001\002\000\042\005\ufff4\015\ufff4\020\ufff4\021" +
    "\ufff4\023\ufff4\024\ufff4\026\ufff4\027\ufff4\031\ufff4\032\ufff4" +
    "\033\ufff4\036\ufff4\037\ufff4\040\ufff4\041\ufff4\042\ufff4\001" +
    "\002\000\012\004\034\005\042\006\041\016\033\001\002" +
    "\000\004\014\054\001\002\000\014\007\uffe1\010\uffe1\011" +
    "\uffe1\012\uffe1\014\uffe1\001\002\000\014\007\uffe2\010\uffe2" +
    "\011\uffe2\012\uffe2\014\uffe2\001\002\000\006\010\045\014" +
    "\053\001\002\000\010\007\uffe6\010\uffe6\014\uffe6\001\002" +
    "\000\014\007\uffe4\010\uffe4\011\050\012\047\014\uffe4\001" +
    "\002\000\010\004\034\005\042\006\041\001\002\000\014" +
    "\007\uffe0\010\uffe0\011\uffe0\012\uffe0\014\uffe0\001\002\000" +
    "\006\007\044\010\045\001\002\000\014\007\uffdf\010\uffdf" +
    "\011\uffdf\012\uffdf\014\uffdf\001\002\000\010\004\034\005" +
    "\042\006\041\001\002\000\010\007\uffe7\010\uffe7\014\uffe7" +
    "\001\002\000\010\004\034\005\042\006\041\001\002\000" +
    "\010\004\034\005\042\006\041\001\002\000\012\007\uffe5" +
    "\010\uffe5\012\047\014\uffe5\001\002\000\014\007\uffe3\010" +
    "\uffe3\011\uffe3\012\uffe3\014\uffe3\001\002\000\042\005\ufff0" +
    "\015\ufff0\020\ufff0\021\ufff0\023\ufff0\024\ufff0\026\ufff0\027" +
    "\ufff0\031\ufff0\032\ufff0\033\ufff0\036\ufff0\037\ufff0\040\ufff0" +
    "\041\ufff0\042\ufff0\001\002\000\042\005\uffef\015\uffef\020" +
    "\uffef\021\uffef\023\uffef\024\uffef\026\uffef\027\uffef\031\uffef" +
    "\032\uffef\033\uffef\036\uffef\037\uffef\040\uffef\041\uffef\042" +
    "\uffef\001\002\000\022\005\027\015\015\020\014\021\007" +
    "\024\013\027\011\033\020\037\012\001\002\000\004\036" +
    "\057\001\002\000\042\005\ufff5\015\ufff5\020\ufff5\021\ufff5" +
    "\023\ufff5\024\ufff5\026\ufff5\027\ufff5\031\ufff5\032\ufff5\033" +
    "\ufff5\036\ufff5\037\ufff5\040\ufff5\041\ufff5\042\ufff5\001\002" +
    "\000\004\002\uffff\001\002\000\022\023\uffe8\026\uffe8\031" +
    "\uffe8\032\uffe8\036\uffe8\040\uffe8\041\uffe8\042\uffe8\001\002" +
    "\000\006\014\ufffe\017\065\001\002\000\004\014\064\001" +
    "\002\000\042\005\ufff7\015\ufff7\020\ufff7\021\ufff7\023\ufff7" +
    "\024\ufff7\026\ufff7\027\ufff7\031\ufff7\032\ufff7\033\ufff7\036" +
    "\ufff7\037\ufff7\040\ufff7\041\ufff7\042\ufff7\001\002\000\004" +
    "\005\062\001\002\000\004\014\ufffd\001\002\000\004\014" +
    "\070\001\002\000\042\005\ufff6\015\ufff6\020\ufff6\021\ufff6" +
    "\023\ufff6\024\ufff6\026\ufff6\027\ufff6\031\ufff6\032\ufff6\033" +
    "\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6\042\ufff6\001\002" +
    "\000\010\004\034\005\042\006\041\001\002\000\006\007" +
    "\073\010\045\001\002\000\004\025\074\001\002\000\022" +
    "\005\027\015\015\020\014\021\007\024\013\027\011\033" +
    "\020\037\012\001\002\000\004\026\076\001\002\000\042" +
    "\005\ufff1\015\ufff1\020\ufff1\021\ufff1\023\ufff1\024\ufff1\026" +
    "\ufff1\027\ufff1\031\ufff1\032\ufff1\033\ufff1\036\ufff1\037\ufff1" +
    "\040\ufff1\041\ufff1\042\ufff1\001\002\000\004\025\100\001" +
    "\002\000\004\040\102\001\002\000\004\042\113\001\002" +
    "\000\004\004\105\001\002\000\006\040\102\042\uffed\001" +
    "\002\000\004\042\uffec\001\002\000\004\043\106\001\002" +
    "\000\022\005\027\015\015\020\014\021\007\024\013\027" +
    "\011\033\020\037\012\001\002\000\010\040\uffea\041\110" +
    "\042\uffea\001\002\000\004\043\111\001\002\000\022\005" +
    "\027\015\015\020\014\021\007\024\013\027\011\033\020" +
    "\037\012\001\002\000\006\040\uffeb\042\uffeb\001\002\000" +
    "\042\005\uffee\015\uffee\020\uffee\021\uffee\023\uffee\024\uffee" +
    "\026\uffee\027\uffee\031\uffee\032\uffee\033\uffee\036\uffee\037" +
    "\uffee\040\uffee\041\uffee\042\uffee\001\002\000\010\004\034" +
    "\005\042\006\041\001\002\000\006\007\116\010\045\001" +
    "\002\000\004\030\117\001\002\000\022\005\027\015\015" +
    "\020\014\021\007\024\013\027\011\033\020\037\012\001" +
    "\002\000\006\031\121\032\122\001\002\000\022\005\027" +
    "\015\015\020\014\021\007\024\013\027\011\033\020\037" +
    "\012\001\002\000\042\005\ufff3\015\ufff3\020\ufff3\021\ufff3" +
    "\023\ufff3\024\ufff3\026\ufff3\027\ufff3\031\ufff3\032\ufff3\033" +
    "\ufff3\036\ufff3\037\ufff3\040\ufff3\041\ufff3\042\ufff3\001\002" +
    "\000\004\032\124\001\002\000\042\005\ufff2\015\ufff2\020" +
    "\ufff2\021\ufff2\023\ufff2\024\ufff2\026\ufff2\027\ufff2\031\ufff2" +
    "\032\ufff2\033\ufff2\036\ufff2\037\ufff2\040\ufff2\041\ufff2\042" +
    "\ufff2\001\002\000\004\023\126\001\002\000\004\002\000" +
    "\001\002\000\004\014\136\001\002\000\006\014\ufffb\017" +
    "\134\001\002\000\006\014\ufffc\017\132\001\002\000\006" +
    "\005\131\016\130\001\002\000\004\014\ufffa\001\002\000" +
    "\006\005\131\016\130\001\002\000\004\014\ufff9\001\002" +
    "\000\042\005\ufff8\015\ufff8\020\ufff8\021\ufff8\023\ufff8\024" +
    "\ufff8\026\ufff8\027\ufff8\031\ufff8\032\ufff8\033\ufff8\036\ufff8" +
    "\037\ufff8\040\ufff8\041\ufff8\042\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\134\000\004\002\004\001\001\000\006\007\015\010" +
    "\016\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\126\001\001\000\006\007\015\010\124\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\066\001\001\000\004\011\062\001\001\000\006\007" +
    "\015\010\060\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\007\015\010\027\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\003\037\004\034\005\035\006\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\037\004\034\005\042\006\036\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\003\037" +
    "\004\034\006\045\001\001\000\002\001\001\000\004\004" +
    "\051\001\001\000\006\003\050\004\034\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\007\015\010\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\003\037\004\034\005\071\006\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\015\010\074\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\013\100\014\102\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\013\103\014\102" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\015\010\106\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\015\010\111\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\003\037\004\034\005\114\006\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\015\010\117\001\001\000\002\001\001\000\006\007\015" +
    "\010\122\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\132\001\001\000\002\001\001\000\004\012\134\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public String errsin = "";
    public void syntax_error(Symbol x){
        errsin += "\nError de Sintaxis en la posicionM: " + (x.left+1) + " , " + (x.right+1);
        throw new UnsupportedOperationException(errsin);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // T ::= pi EL pd 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("T",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // T ::= id 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("T",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // T ::= num 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("T",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // E ::= T 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("E",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // E ::= E op_ari T 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("E",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EA ::= E 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EA",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EA ::= E op_rel E 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EA",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EL ::= EA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EL",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EL ::= EL op_log EA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EL",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // IS ::= I IS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IS",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // IS ::= I 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IS",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // CASO ::= caso num dospuntos IS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CASO",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // CASO ::= caso num dospuntos IS deotromodo dospuntos IS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CASO",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // CASOS ::= CASO CASOS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CASOS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // CASOS ::= CASO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CASOS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // I ::= segun id hacer CASOS finsegun 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // I ::= id asig cadena puntocoma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // I ::= id asig EL puntocoma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // I ::= mientras pi EL pd hacer IS finmientras 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // I ::= si pi EL pd entonces IS sino IS finsi 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // I ::= si pi EL pd entonces IS finsi 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // I ::= para id asig num hasta id IS finpara 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // I ::= para id asig num hasta id paso num IS finpara 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // I ::= leer LV puntocoma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // I ::= tipo LV puntocoma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // I ::= escribir L puntocoma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("I",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // L ::= cadena coma L 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("L",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // L ::= id coma L 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("L",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // L ::= cadena 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("L",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // L ::= id 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("L",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LV ::= id coma LV 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LV",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LV ::= id 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LV",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // S ::= programa IS finprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= programa id IS finprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

