
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 07 19:39:27 COT 2025
//----------------------------------------------------

package anal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int op_rel = 7;
  public static final int para = 25;
  public static final int cadena = 12;
  public static final int op_ari = 8;
  public static final int finsegun = 32;
  public static final int paso = 27;
  public static final int tipo = 11;
  public static final int caso = 30;
  public static final int coma = 13;
  public static final int op_log = 6;
  public static final int deotromodo = 31;
  public static final int finpara = 28;
  public static final int mientras = 18;
  public static final int sino = 23;
  public static final int finsi = 24;
  public static final int hacer = 19;
  public static final int num = 2;
  public static final int programa = 16;
  public static final int segun = 29;
  public static final int EOF = 0;
  public static final int asig = 9;
  public static final int id = 3;
  public static final int entonces = 22;
  public static final int puntocoma = 10;
  public static final int escribir = 15;
  public static final int hasta = 26;
  public static final int error = 1;
  public static final int finmientras = 20;
  public static final int pi = 4;
  public static final int si = 21;
  public static final int leer = 14;
  public static final int dospuntos = 33;
  public static final int finprograma = 17;
  public static final int pd = 5;
}

